# Generated by Django 5.2.8 on 2025-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Default question'),
            preserve_default=False,
        ),
    ]
